// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
*/
import "C"
import "unsafe"

// newGenerated wraps an attached channel in its generated type, or returns nil for other classes.
func newGenerated(class C.Phidget_ChannelClass, channel C.PhidgetHandle) Phidget {
	switch class {
	case C.PHIDCHCLASS_BLDCMOTOR:
		return &PhidgetBLDCMotor{phidget{handle: channel}, C.PhidgetBLDCMotorHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_CAPACITIVETOUCH:
		return &PhidgetCapacitiveTouch{phidget{handle: channel}, C.PhidgetCapacitiveTouchHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_DCMOTOR:
		return &PhidgetDCMotor{phidget{handle: channel}, C.PhidgetDCMotorHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_ENCODER:
		return &PhidgetEncoder{phidget{handle: channel}, C.PhidgetEncoderHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_FREQUENCYCOUNTER:
		return &PhidgetFrequencyCounter{phidget{handle: channel}, C.PhidgetFrequencyCounterHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_GPS:
		return &PhidgetGPS{phidget{handle: channel}, C.PhidgetGPSHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_GYROSCOPE:
		return &PhidgetGyroscope{phidget{handle: channel}, C.PhidgetGyroscopeHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_MAGNETOMETER:
		return &PhidgetMagnetometer{phidget{handle: channel}, C.PhidgetMagnetometerHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_PHSENSOR:
		return &PhidgetPHSensor{phidget{handle: channel}, C.PhidgetPHSensorHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_PRESSURESENSOR:
		return &PhidgetPressureSensor{phidget{handle: channel}, C.PhidgetPressureSensorHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_RCSERVO:
		return &PhidgetRCServo{phidget{handle: channel}, C.PhidgetRCServoHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_RESISTANCEINPUT:
		return &PhidgetResistanceInput{phidget{handle: channel}, C.PhidgetResistanceInputHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_SPATIAL:
		return &PhidgetSpatial{phidget{handle: channel}, C.PhidgetSpatialHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_STEPPER:
		return &PhidgetStepper{phidget{handle: channel}, C.PhidgetStepperHandle(unsafe.Pointer(channel))}
	case C.PHIDCHCLASS_VOLTAGEOUTPUT:
		return &PhidgetVoltageOutput{phidget{handle: channel}, C.PhidgetVoltageOutputHandle(unsafe.Pointer(channel))}
	}
	return nil
}
