// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetBLDCMotor wraps a PhidgetBLDCMotor channel.
type PhidgetBLDCMotor struct {
	phidget
	handle C.PhidgetBLDCMotorHandle
}

// Create creates a PhidgetBLDCMotor handle.
func (p *PhidgetBLDCMotor) Create() {
	C.PhidgetBLDCMotor_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetBLDCMotor) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetBLDCMotor_delete(&p.handle))
}

// EnableFailsafe wraps PhidgetBLDCMotor_enableFailsafe.
func (p *PhidgetBLDCMotor) EnableFailsafe(failsafeTime uint32) error {
	return p.phidgetError(C.PhidgetBLDCMotor_enableFailsafe(p.handle, C.uint32_t(failsafeTime)))
}

// AddPositionOffset wraps PhidgetBLDCMotor_addPositionOffset.
func (p *PhidgetBLDCMotor) AddPositionOffset(positionOffset float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_addPositionOffset(p.handle, C.double(positionOffset)))
}

// ResetFailsafe wraps PhidgetBLDCMotor_resetFailsafe.
func (p *PhidgetBLDCMotor) ResetFailsafe() error {
	return p.phidgetError(C.PhidgetBLDCMotor_resetFailsafe(p.handle))
}

// SetAcceleration wraps PhidgetBLDCMotor_setAcceleration.
func (p *PhidgetBLDCMotor) SetAcceleration(acceleration float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setAcceleration(p.handle, C.double(acceleration)))
}

// GetAcceleration wraps PhidgetBLDCMotor_getAcceleration.
func (p *PhidgetBLDCMotor) GetAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getAcceleration(p.handle, r) })
}

// GetMinAcceleration wraps PhidgetBLDCMotor_getMinAcceleration.
func (p *PhidgetBLDCMotor) GetMinAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinAcceleration(p.handle, r) })
}

// GetMaxAcceleration wraps PhidgetBLDCMotor_getMaxAcceleration.
func (p *PhidgetBLDCMotor) GetMaxAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxAcceleration(p.handle, r) })
}

// GetBrakingStrength wraps PhidgetBLDCMotor_getBrakingStrength.
func (p *PhidgetBLDCMotor) GetBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getBrakingStrength(p.handle, r) })
}

// GetMinBrakingStrength wraps PhidgetBLDCMotor_getMinBrakingStrength.
func (p *PhidgetBLDCMotor) GetMinBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinBrakingStrength(p.handle, r) })
}

// GetMaxBrakingStrength wraps PhidgetBLDCMotor_getMaxBrakingStrength.
func (p *PhidgetBLDCMotor) GetMaxBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxBrakingStrength(p.handle, r) })
}

// SetCurrentLimit wraps PhidgetBLDCMotor_setCurrentLimit.
func (p *PhidgetBLDCMotor) SetCurrentLimit(currentLimit float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setCurrentLimit(p.handle, C.double(currentLimit)))
}

// GetCurrentLimit wraps PhidgetBLDCMotor_getCurrentLimit.
func (p *PhidgetBLDCMotor) GetCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getCurrentLimit(p.handle, r) })
}

// GetMinCurrentLimit wraps PhidgetBLDCMotor_getMinCurrentLimit.
func (p *PhidgetBLDCMotor) GetMinCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinCurrentLimit(p.handle, r) })
}

// GetMaxCurrentLimit wraps PhidgetBLDCMotor_getMaxCurrentLimit.
func (p *PhidgetBLDCMotor) GetMaxCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxCurrentLimit(p.handle, r) })
}

// SetDataInterval wraps PhidgetBLDCMotor_setDataInterval.
func (p *PhidgetBLDCMotor) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetBLDCMotor_getDataInterval.
func (p *PhidgetBLDCMotor) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetBLDCMotor_getMinDataInterval.
func (p *PhidgetBLDCMotor) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetBLDCMotor_getMaxDataInterval.
func (p *PhidgetBLDCMotor) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetBLDCMotor_setDataRate.
func (p *PhidgetBLDCMotor) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetBLDCMotor_getDataRate.
func (p *PhidgetBLDCMotor) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetBLDCMotor_getMinDataRate.
func (p *PhidgetBLDCMotor) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetBLDCMotor_getMaxDataRate.
func (p *PhidgetBLDCMotor) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxDataRate(p.handle, r) })
}

// GetMinFailsafeTime wraps PhidgetBLDCMotor_getMinFailsafeTime.
func (p *PhidgetBLDCMotor) GetMinFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinFailsafeTime(p.handle, r) })
}

// GetMaxFailsafeTime wraps PhidgetBLDCMotor_getMaxFailsafeTime.
func (p *PhidgetBLDCMotor) GetMaxFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxFailsafeTime(p.handle, r) })
}

// GetPosition wraps PhidgetBLDCMotor_getPosition.
func (p *PhidgetBLDCMotor) GetPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getPosition(p.handle, r) })
}

// GetMinPosition wraps PhidgetBLDCMotor_getMinPosition.
func (p *PhidgetBLDCMotor) GetMinPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinPosition(p.handle, r) })
}

// GetMaxPosition wraps PhidgetBLDCMotor_getMaxPosition.
func (p *PhidgetBLDCMotor) GetMaxPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxPosition(p.handle, r) })
}

// SetRescaleFactor wraps PhidgetBLDCMotor_setRescaleFactor.
func (p *PhidgetBLDCMotor) SetRescaleFactor(rescaleFactor float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setRescaleFactor(p.handle, C.double(rescaleFactor)))
}

// GetRescaleFactor wraps PhidgetBLDCMotor_getRescaleFactor.
func (p *PhidgetBLDCMotor) GetRescaleFactor() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getRescaleFactor(p.handle, r) })
}

// SetStallVelocity wraps PhidgetBLDCMotor_setStallVelocity.
func (p *PhidgetBLDCMotor) SetStallVelocity(stallVelocity float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setStallVelocity(p.handle, C.double(stallVelocity)))
}

// GetStallVelocity wraps PhidgetBLDCMotor_getStallVelocity.
func (p *PhidgetBLDCMotor) GetStallVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getStallVelocity(p.handle, r) })
}

// GetMinStallVelocity wraps PhidgetBLDCMotor_getMinStallVelocity.
func (p *PhidgetBLDCMotor) GetMinStallVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinStallVelocity(p.handle, r) })
}

// GetMaxStallVelocity wraps PhidgetBLDCMotor_getMaxStallVelocity.
func (p *PhidgetBLDCMotor) GetMaxStallVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxStallVelocity(p.handle, r) })
}

// SetTargetBrakingStrength wraps PhidgetBLDCMotor_setTargetBrakingStrength.
func (p *PhidgetBLDCMotor) SetTargetBrakingStrength(targetBrakingStrength float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setTargetBrakingStrength(p.handle, C.double(targetBrakingStrength)))
}

// GetTargetBrakingStrength wraps PhidgetBLDCMotor_getTargetBrakingStrength.
func (p *PhidgetBLDCMotor) GetTargetBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getTargetBrakingStrength(p.handle, r) })
}

// SetTargetVelocity wraps PhidgetBLDCMotor_setTargetVelocity.
func (p *PhidgetBLDCMotor) SetTargetVelocity(targetVelocity float64) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setTargetVelocity(p.handle, C.double(targetVelocity)))
}

// GetTargetVelocity wraps PhidgetBLDCMotor_getTargetVelocity.
func (p *PhidgetBLDCMotor) GetTargetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getTargetVelocity(p.handle, r) })
}

// GetVelocity wraps PhidgetBLDCMotor_getVelocity.
func (p *PhidgetBLDCMotor) GetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getVelocity(p.handle, r) })
}

// GetMinVelocity wraps PhidgetBLDCMotor_getMinVelocity.
func (p *PhidgetBLDCMotor) GetMinVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMinVelocity(p.handle, r) })
}

// GetMaxVelocity wraps PhidgetBLDCMotor_getMaxVelocity.
func (p *PhidgetBLDCMotor) GetMaxVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetBLDCMotor_getMaxVelocity(p.handle, r) })
}

// SetOnBrakingStrengthChangeHandler wraps PhidgetBLDCMotor_setOnBrakingStrengthChangeHandler. The handler runs on a C thread.
func (p *PhidgetBLDCMotor) SetOnBrakingStrengthChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setOnBrakingStrengthChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnPositionChangeHandler wraps PhidgetBLDCMotor_setOnPositionChangeHandler. The handler runs on a C thread.
func (p *PhidgetBLDCMotor) SetOnPositionChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setOnPositionChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnVelocityUpdateHandler wraps PhidgetBLDCMotor_setOnVelocityUpdateHandler. The handler runs on a C thread.
func (p *PhidgetBLDCMotor) SetOnVelocityUpdateHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetBLDCMotor_setOnVelocityUpdateHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
