// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetCapacitiveTouch wraps a PhidgetCapacitiveTouch channel.
type PhidgetCapacitiveTouch struct {
	phidget
	handle C.PhidgetCapacitiveTouchHandle
}

// Create creates a PhidgetCapacitiveTouch handle.
func (p *PhidgetCapacitiveTouch) Create() {
	C.PhidgetCapacitiveTouch_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetCapacitiveTouch) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetCapacitiveTouch_delete(&p.handle))
}

// SetDataInterval wraps PhidgetCapacitiveTouch_setDataInterval.
func (p *PhidgetCapacitiveTouch) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetCapacitiveTouch_getDataInterval.
func (p *PhidgetCapacitiveTouch) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetCapacitiveTouch_getMinDataInterval.
func (p *PhidgetCapacitiveTouch) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetCapacitiveTouch_getMinDataInterval(p.handle, r)
	})
}

// GetMaxDataInterval wraps PhidgetCapacitiveTouch_getMaxDataInterval.
func (p *PhidgetCapacitiveTouch) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetCapacitiveTouch_getMaxDataInterval(p.handle, r)
	})
}

// SetDataRate wraps PhidgetCapacitiveTouch_setDataRate.
func (p *PhidgetCapacitiveTouch) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetCapacitiveTouch_getDataRate.
func (p *PhidgetCapacitiveTouch) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetCapacitiveTouch_getMinDataRate.
func (p *PhidgetCapacitiveTouch) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetCapacitiveTouch_getMaxDataRate.
func (p *PhidgetCapacitiveTouch) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMaxDataRate(p.handle, r) })
}

// SetSensitivity wraps PhidgetCapacitiveTouch_setSensitivity.
func (p *PhidgetCapacitiveTouch) SetSensitivity(sensitivity float64) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setSensitivity(p.handle, C.double(sensitivity)))
}

// GetSensitivity wraps PhidgetCapacitiveTouch_getSensitivity.
func (p *PhidgetCapacitiveTouch) GetSensitivity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getSensitivity(p.handle, r) })
}

// GetMinSensitivity wraps PhidgetCapacitiveTouch_getMinSensitivity.
func (p *PhidgetCapacitiveTouch) GetMinSensitivity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMinSensitivity(p.handle, r) })
}

// GetMaxSensitivity wraps PhidgetCapacitiveTouch_getMaxSensitivity.
func (p *PhidgetCapacitiveTouch) GetMaxSensitivity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMaxSensitivity(p.handle, r) })
}

// GetIsTouched wraps PhidgetCapacitiveTouch_getIsTouched.
func (p *PhidgetCapacitiveTouch) GetIsTouched() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getIsTouched(p.handle, r) })
}

// GetTouchValue wraps PhidgetCapacitiveTouch_getTouchValue.
func (p *PhidgetCapacitiveTouch) GetTouchValue() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getTouchValue(p.handle, r) })
}

// GetMinTouchValue wraps PhidgetCapacitiveTouch_getMinTouchValue.
func (p *PhidgetCapacitiveTouch) GetMinTouchValue() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMinTouchValue(p.handle, r) })
}

// GetMaxTouchValue wraps PhidgetCapacitiveTouch_getMaxTouchValue.
func (p *PhidgetCapacitiveTouch) GetMaxTouchValue() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetCapacitiveTouch_getMaxTouchValue(p.handle, r) })
}

// SetTouchValueChangeTrigger wraps PhidgetCapacitiveTouch_setTouchValueChangeTrigger.
func (p *PhidgetCapacitiveTouch) SetTouchValueChangeTrigger(touchValueChangeTrigger float64) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setTouchValueChangeTrigger(p.handle, C.double(touchValueChangeTrigger)))
}

// GetTouchValueChangeTrigger wraps PhidgetCapacitiveTouch_getTouchValueChangeTrigger.
func (p *PhidgetCapacitiveTouch) GetTouchValueChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetCapacitiveTouch_getTouchValueChangeTrigger(p.handle, r)
	})
}

// GetMinTouchValueChangeTrigger wraps PhidgetCapacitiveTouch_getMinTouchValueChangeTrigger.
func (p *PhidgetCapacitiveTouch) GetMinTouchValueChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetCapacitiveTouch_getMinTouchValueChangeTrigger(p.handle, r)
	})
}

// GetMaxTouchValueChangeTrigger wraps PhidgetCapacitiveTouch_getMaxTouchValueChangeTrigger.
func (p *PhidgetCapacitiveTouch) GetMaxTouchValueChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetCapacitiveTouch_getMaxTouchValueChangeTrigger(p.handle, r)
	})
}

// SetOnTouchHandler wraps PhidgetCapacitiveTouch_setOnTouchHandler. The handler runs on a C thread.
func (p *PhidgetCapacitiveTouch) SetOnTouchHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setOnTouchHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnTouchEndHandler wraps PhidgetCapacitiveTouch_setOnTouchEndHandler. The handler runs on a C thread.
func (p *PhidgetCapacitiveTouch) SetOnTouchEndHandler(f func()) error {
	return p.phidgetError(C.PhidgetCapacitiveTouch_setOnTouchEndHandler(p.handle, (C.phidget_void_fcn)(unsafe.Pointer(C.cvoidcallback)), p.save(f)))
}
