// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetDCMotor wraps a PhidgetDCMotor channel.
type PhidgetDCMotor struct {
	phidget
	handle C.PhidgetDCMotorHandle
}

// Create creates a PhidgetDCMotor handle.
func (p *PhidgetDCMotor) Create() {
	C.PhidgetDCMotor_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetDCMotor) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetDCMotor_delete(&p.handle))
}

// EnableFailsafe wraps PhidgetDCMotor_enableFailsafe.
func (p *PhidgetDCMotor) EnableFailsafe(failsafeTime uint32) error {
	return p.phidgetError(C.PhidgetDCMotor_enableFailsafe(p.handle, C.uint32_t(failsafeTime)))
}

// ResetFailsafe wraps PhidgetDCMotor_resetFailsafe.
func (p *PhidgetDCMotor) ResetFailsafe() error {
	return p.phidgetError(C.PhidgetDCMotor_resetFailsafe(p.handle))
}

// SetAcceleration wraps PhidgetDCMotor_setAcceleration.
func (p *PhidgetDCMotor) SetAcceleration(acceleration float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setAcceleration(p.handle, C.double(acceleration)))
}

// GetAcceleration wraps PhidgetDCMotor_getAcceleration.
func (p *PhidgetDCMotor) GetAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getAcceleration(p.handle, r) })
}

// GetMinAcceleration wraps PhidgetDCMotor_getMinAcceleration.
func (p *PhidgetDCMotor) GetMinAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinAcceleration(p.handle, r) })
}

// GetMaxAcceleration wraps PhidgetDCMotor_getMaxAcceleration.
func (p *PhidgetDCMotor) GetMaxAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxAcceleration(p.handle, r) })
}

// GetBackEMF wraps PhidgetDCMotor_getBackEMF.
func (p *PhidgetDCMotor) GetBackEMF() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getBackEMF(p.handle, r) })
}

// SetBackEMFSensingState wraps PhidgetDCMotor_setBackEMFSensingState.
func (p *PhidgetDCMotor) SetBackEMFSensingState(backEMFSensingState bool) error {
	return p.phidgetError(C.PhidgetDCMotor_setBackEMFSensingState(p.handle, boolToCInt(backEMFSensingState)))
}

// GetBackEMFSensingState wraps PhidgetDCMotor_getBackEMFSensingState.
func (p *PhidgetDCMotor) GetBackEMFSensingState() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetDCMotor_getBackEMFSensingState(p.handle, r) })
}

// GetBrakingStrength wraps PhidgetDCMotor_getBrakingStrength.
func (p *PhidgetDCMotor) GetBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getBrakingStrength(p.handle, r) })
}

// GetMinBrakingStrength wraps PhidgetDCMotor_getMinBrakingStrength.
func (p *PhidgetDCMotor) GetMinBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinBrakingStrength(p.handle, r) })
}

// GetMaxBrakingStrength wraps PhidgetDCMotor_getMaxBrakingStrength.
func (p *PhidgetDCMotor) GetMaxBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxBrakingStrength(p.handle, r) })
}

// SetCurrentLimit wraps PhidgetDCMotor_setCurrentLimit.
func (p *PhidgetDCMotor) SetCurrentLimit(currentLimit float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setCurrentLimit(p.handle, C.double(currentLimit)))
}

// GetCurrentLimit wraps PhidgetDCMotor_getCurrentLimit.
func (p *PhidgetDCMotor) GetCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getCurrentLimit(p.handle, r) })
}

// GetMinCurrentLimit wraps PhidgetDCMotor_getMinCurrentLimit.
func (p *PhidgetDCMotor) GetMinCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinCurrentLimit(p.handle, r) })
}

// GetMaxCurrentLimit wraps PhidgetDCMotor_getMaxCurrentLimit.
func (p *PhidgetDCMotor) GetMaxCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxCurrentLimit(p.handle, r) })
}

// SetCurrentRegulatorGain wraps PhidgetDCMotor_setCurrentRegulatorGain.
func (p *PhidgetDCMotor) SetCurrentRegulatorGain(currentRegulatorGain float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setCurrentRegulatorGain(p.handle, C.double(currentRegulatorGain)))
}

// GetCurrentRegulatorGain wraps PhidgetDCMotor_getCurrentRegulatorGain.
func (p *PhidgetDCMotor) GetCurrentRegulatorGain() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getCurrentRegulatorGain(p.handle, r) })
}

// GetMinCurrentRegulatorGain wraps PhidgetDCMotor_getMinCurrentRegulatorGain.
func (p *PhidgetDCMotor) GetMinCurrentRegulatorGain() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinCurrentRegulatorGain(p.handle, r) })
}

// GetMaxCurrentRegulatorGain wraps PhidgetDCMotor_getMaxCurrentRegulatorGain.
func (p *PhidgetDCMotor) GetMaxCurrentRegulatorGain() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxCurrentRegulatorGain(p.handle, r) })
}

// SetDataInterval wraps PhidgetDCMotor_setDataInterval.
func (p *PhidgetDCMotor) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetDCMotor_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetDCMotor_getDataInterval.
func (p *PhidgetDCMotor) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetDCMotor_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetDCMotor_getMinDataInterval.
func (p *PhidgetDCMotor) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetDCMotor_getMaxDataInterval.
func (p *PhidgetDCMotor) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetDCMotor_setDataRate.
func (p *PhidgetDCMotor) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetDCMotor_getDataRate.
func (p *PhidgetDCMotor) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetDCMotor_getMinDataRate.
func (p *PhidgetDCMotor) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetDCMotor_getMaxDataRate.
func (p *PhidgetDCMotor) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxDataRate(p.handle, r) })
}

// GetMinFailsafeTime wraps PhidgetDCMotor_getMinFailsafeTime.
func (p *PhidgetDCMotor) GetMinFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinFailsafeTime(p.handle, r) })
}

// GetMaxFailsafeTime wraps PhidgetDCMotor_getMaxFailsafeTime.
func (p *PhidgetDCMotor) GetMaxFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxFailsafeTime(p.handle, r) })
}

// SetFanMode wraps PhidgetDCMotor_setFanMode.
func (p *PhidgetDCMotor) SetFanMode(fanMode int) error {
	return p.phidgetError(C.PhidgetDCMotor_setFanMode(p.handle, C.Phidget_FanMode(fanMode)))
}

// GetFanMode wraps PhidgetDCMotor_getFanMode.
func (p *PhidgetDCMotor) GetFanMode() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_FanMode) C.PhidgetReturnCode { return C.PhidgetDCMotor_getFanMode(p.handle, r) }, func(r C.Phidget_FanMode) int { return int(r) })
}

// SetTargetBrakingStrength wraps PhidgetDCMotor_setTargetBrakingStrength.
func (p *PhidgetDCMotor) SetTargetBrakingStrength(targetBrakingStrength float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setTargetBrakingStrength(p.handle, C.double(targetBrakingStrength)))
}

// GetTargetBrakingStrength wraps PhidgetDCMotor_getTargetBrakingStrength.
func (p *PhidgetDCMotor) GetTargetBrakingStrength() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getTargetBrakingStrength(p.handle, r) })
}

// SetTargetVelocity wraps PhidgetDCMotor_setTargetVelocity.
func (p *PhidgetDCMotor) SetTargetVelocity(targetVelocity float64) error {
	return p.phidgetError(C.PhidgetDCMotor_setTargetVelocity(p.handle, C.double(targetVelocity)))
}

// GetTargetVelocity wraps PhidgetDCMotor_getTargetVelocity.
func (p *PhidgetDCMotor) GetTargetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getTargetVelocity(p.handle, r) })
}

// GetVelocity wraps PhidgetDCMotor_getVelocity.
func (p *PhidgetDCMotor) GetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getVelocity(p.handle, r) })
}

// GetMinVelocity wraps PhidgetDCMotor_getMinVelocity.
func (p *PhidgetDCMotor) GetMinVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMinVelocity(p.handle, r) })
}

// GetMaxVelocity wraps PhidgetDCMotor_getMaxVelocity.
func (p *PhidgetDCMotor) GetMaxVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetDCMotor_getMaxVelocity(p.handle, r) })
}

// SetOnBackEMFChangeHandler wraps PhidgetDCMotor_setOnBackEMFChangeHandler. The handler runs on a C thread.
func (p *PhidgetDCMotor) SetOnBackEMFChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetDCMotor_setOnBackEMFChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnBrakingStrengthChangeHandler wraps PhidgetDCMotor_setOnBrakingStrengthChangeHandler. The handler runs on a C thread.
func (p *PhidgetDCMotor) SetOnBrakingStrengthChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetDCMotor_setOnBrakingStrengthChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnVelocityUpdateHandler wraps PhidgetDCMotor_setOnVelocityUpdateHandler. The handler runs on a C thread.
func (p *PhidgetDCMotor) SetOnVelocityUpdateHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetDCMotor_setOnVelocityUpdateHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
