// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetEncoder wraps a PhidgetEncoder channel.
type PhidgetEncoder struct {
	phidget
	handle C.PhidgetEncoderHandle
}

// Create creates a PhidgetEncoder handle.
func (p *PhidgetEncoder) Create() {
	C.PhidgetEncoder_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetEncoder) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetEncoder_delete(&p.handle))
}

// SetEnabled wraps PhidgetEncoder_setEnabled.
func (p *PhidgetEncoder) SetEnabled(enabled bool) error {
	return p.phidgetError(C.PhidgetEncoder_setEnabled(p.handle, boolToCInt(enabled)))
}

// GetEnabled wraps PhidgetEncoder_getEnabled.
func (p *PhidgetEncoder) GetEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetEncoder_getEnabled(p.handle, r) })
}

// SetDataInterval wraps PhidgetEncoder_setDataInterval.
func (p *PhidgetEncoder) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetEncoder_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetEncoder_getDataInterval.
func (p *PhidgetEncoder) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetEncoder_getMinDataInterval.
func (p *PhidgetEncoder) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetEncoder_getMaxDataInterval.
func (p *PhidgetEncoder) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetEncoder_setDataRate.
func (p *PhidgetEncoder) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetEncoder_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetEncoder_getDataRate.
func (p *PhidgetEncoder) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetEncoder_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetEncoder_getMinDataRate.
func (p *PhidgetEncoder) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetEncoder_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetEncoder_getMaxDataRate.
func (p *PhidgetEncoder) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetEncoder_getMaxDataRate(p.handle, r) })
}

// GetIndexPosition wraps PhidgetEncoder_getIndexPosition.
func (p *PhidgetEncoder) GetIndexPosition() (int64, error) {
	return getInt64(&p.phidget, func(r *C.int64_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getIndexPosition(p.handle, r) })
}

// SetIOMode wraps PhidgetEncoder_setIOMode.
func (p *PhidgetEncoder) SetIOMode(IOMode int) error {
	return p.phidgetError(C.PhidgetEncoder_setIOMode(p.handle, C.Phidget_EncoderIOMode(IOMode)))
}

// GetIOMode wraps PhidgetEncoder_getIOMode.
func (p *PhidgetEncoder) GetIOMode() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_EncoderIOMode) C.PhidgetReturnCode { return C.PhidgetEncoder_getIOMode(p.handle, r) }, func(r C.Phidget_EncoderIOMode) int { return int(r) })
}

// SetPosition wraps PhidgetEncoder_setPosition.
func (p *PhidgetEncoder) SetPosition(position int64) error {
	return p.phidgetError(C.PhidgetEncoder_setPosition(p.handle, C.int64_t(position)))
}

// GetPosition wraps PhidgetEncoder_getPosition.
func (p *PhidgetEncoder) GetPosition() (int64, error) {
	return getInt64(&p.phidget, func(r *C.int64_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getPosition(p.handle, r) })
}

// SetPositionChangeTrigger wraps PhidgetEncoder_setPositionChangeTrigger.
func (p *PhidgetEncoder) SetPositionChangeTrigger(positionChangeTrigger uint32) error {
	return p.phidgetError(C.PhidgetEncoder_setPositionChangeTrigger(p.handle, C.uint32_t(positionChangeTrigger)))
}

// GetPositionChangeTrigger wraps PhidgetEncoder_getPositionChangeTrigger.
func (p *PhidgetEncoder) GetPositionChangeTrigger() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetEncoder_getPositionChangeTrigger(p.handle, r) })
}

// GetMinPositionChangeTrigger wraps PhidgetEncoder_getMinPositionChangeTrigger.
func (p *PhidgetEncoder) GetMinPositionChangeTrigger() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetEncoder_getMinPositionChangeTrigger(p.handle, r)
	})
}

// GetMaxPositionChangeTrigger wraps PhidgetEncoder_getMaxPositionChangeTrigger.
func (p *PhidgetEncoder) GetMaxPositionChangeTrigger() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetEncoder_getMaxPositionChangeTrigger(p.handle, r)
	})
}

// SetOnPositionChangeHandler wraps PhidgetEncoder_setOnPositionChangeHandler. The handler runs on a C thread.
func (p *PhidgetEncoder) SetOnPositionChangeHandler(f func(int, float64, bool)) error {
	return p.phidgetError(C.PhidgetEncoder_setOnPositionChangeHandler(p.handle, (C.phidget_encoder_fcn)(unsafe.Pointer(C.cencodercallback)), p.save(f)))
}
