// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
*/
import "C"

// FrequencyCounterFilterType values.
const (
	FrequencyCounterFilterTypeZeroCrossing = C.FILTER_TYPE_ZERO_CROSSING
	FrequencyCounterFilterTypeLogicLevel   = C.FILTER_TYPE_LOGIC_LEVEL
)

// RCServoVoltage values.
const (
	RCServoVoltage5V  = C.RCSERVO_VOLTAGE_5V
	RCServoVoltage6V  = C.RCSERVO_VOLTAGE_6V
	RCServoVoltage74V = C.RCSERVO_VOLTAGE_7_4V
)

// StepperControlMode values.
const (
	StepperControlModeStep = C.CONTROL_MODE_STEP
	StepperControlModeRun  = C.CONTROL_MODE_RUN
)

// VoltageOutputRange values.
const (
	VoltageOutputRange10V = C.VOLTAGE_OUTPUT_RANGE_10V
	VoltageOutputRange5V  = C.VOLTAGE_OUTPUT_RANGE_5V
)

// EncoderIOMode values.
const (
	EncoderIOModePushPull         = C.ENCODER_IO_MODE_PUSH_PULL
	EncoderIOModeLineDriver2K2    = C.ENCODER_IO_MODE_LINE_DRIVER_2K2
	EncoderIOModeLineDriver10K    = C.ENCODER_IO_MODE_LINE_DRIVER_10K
	EncoderIOModeOpenCollector2K2 = C.ENCODER_IO_MODE_OPEN_COLLECTOR_2K2
	EncoderIOModeOpenCollector10K = C.ENCODER_IO_MODE_OPEN_COLLECTOR_10K
)

// FanMode values.
const (
	FanModeOff  = C.FAN_MODE_OFF
	FanModeOn   = C.FAN_MODE_ON
	FanModeAuto = C.FAN_MODE_AUTO
)

// InputMode values.
const (
	InputModeNpn = C.INPUT_MODE_NPN
	InputModePnp = C.INPUT_MODE_PNP
)

// PowerSupply values.
const (
	PowerSupplyOff = C.POWER_SUPPLY_OFF
	PowerSupply12V = C.POWER_SUPPLY_12V
	PowerSupply24V = C.POWER_SUPPLY_24V
)

// RTDWireSetup values.
const (
	RTDWireSetup2WIRE = C.RTD_WIRE_SETUP_2WIRE
	RTDWireSetup3WIRE = C.RTD_WIRE_SETUP_3WIRE
	RTDWireSetup4WIRE = C.RTD_WIRE_SETUP_4WIRE
)

// SpatialAlgorithm values.
const (
	SpatialAlgorithmNone = C.SPATIAL_ALGORITHM_NONE
	SpatialAlgorithmAhrs = C.SPATIAL_ALGORITHM_AHRS
	SpatialAlgorithmImu  = C.SPATIAL_ALGORITHM_IMU
)
