// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetFrequencyCounter wraps a PhidgetFrequencyCounter channel.
type PhidgetFrequencyCounter struct {
	phidget
	handle C.PhidgetFrequencyCounterHandle
}

// Create creates a PhidgetFrequencyCounter handle.
func (p *PhidgetFrequencyCounter) Create() {
	C.PhidgetFrequencyCounter_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetFrequencyCounter) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetFrequencyCounter_delete(&p.handle))
}

// Reset wraps PhidgetFrequencyCounter_reset.
func (p *PhidgetFrequencyCounter) Reset() error {
	return p.phidgetError(C.PhidgetFrequencyCounter_reset(p.handle))
}

// GetCount wraps PhidgetFrequencyCounter_getCount.
func (p *PhidgetFrequencyCounter) GetCount() (uint64, error) {
	return getUint64(&p.phidget, func(r *C.uint64_t) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getCount(p.handle, r) })
}

// SetEnabled wraps PhidgetFrequencyCounter_setEnabled.
func (p *PhidgetFrequencyCounter) SetEnabled(enabled bool) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setEnabled(p.handle, boolToCInt(enabled)))
}

// GetEnabled wraps PhidgetFrequencyCounter_getEnabled.
func (p *PhidgetFrequencyCounter) GetEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getEnabled(p.handle, r) })
}

// SetDataInterval wraps PhidgetFrequencyCounter_setDataInterval.
func (p *PhidgetFrequencyCounter) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetFrequencyCounter_getDataInterval.
func (p *PhidgetFrequencyCounter) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetFrequencyCounter_getMinDataInterval.
func (p *PhidgetFrequencyCounter) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getMinDataInterval(p.handle, r)
	})
}

// GetMaxDataInterval wraps PhidgetFrequencyCounter_getMaxDataInterval.
func (p *PhidgetFrequencyCounter) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getMaxDataInterval(p.handle, r)
	})
}

// SetDataRate wraps PhidgetFrequencyCounter_setDataRate.
func (p *PhidgetFrequencyCounter) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetFrequencyCounter_getDataRate.
func (p *PhidgetFrequencyCounter) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetFrequencyCounter_getMinDataRate.
func (p *PhidgetFrequencyCounter) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetFrequencyCounter_getMaxDataRate.
func (p *PhidgetFrequencyCounter) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getMaxDataRate(p.handle, r) })
}

// SetFilterType wraps PhidgetFrequencyCounter_setFilterType.
func (p *PhidgetFrequencyCounter) SetFilterType(filterType int) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setFilterType(p.handle, C.PhidgetFrequencyCounter_FilterType(filterType)))
}

// GetFilterType wraps PhidgetFrequencyCounter_getFilterType.
func (p *PhidgetFrequencyCounter) GetFilterType() (int, error) {
	return get(&p.phidget, func(r *C.PhidgetFrequencyCounter_FilterType) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getFilterType(p.handle, r)
	}, func(r C.PhidgetFrequencyCounter_FilterType) int { return int(r) })
}

// GetFrequency wraps PhidgetFrequencyCounter_getFrequency.
func (p *PhidgetFrequencyCounter) GetFrequency() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getFrequency(p.handle, r) })
}

// GetMaxFrequency wraps PhidgetFrequencyCounter_getMaxFrequency.
func (p *PhidgetFrequencyCounter) GetMaxFrequency() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getMaxFrequency(p.handle, r) })
}

// SetFrequencyCutoff wraps PhidgetFrequencyCounter_setFrequencyCutoff.
func (p *PhidgetFrequencyCounter) SetFrequencyCutoff(frequencyCutoff float64) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setFrequencyCutoff(p.handle, C.double(frequencyCutoff)))
}

// GetFrequencyCutoff wraps PhidgetFrequencyCounter_getFrequencyCutoff.
func (p *PhidgetFrequencyCounter) GetFrequencyCutoff() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getFrequencyCutoff(p.handle, r)
	})
}

// GetMinFrequencyCutoff wraps PhidgetFrequencyCounter_getMinFrequencyCutoff.
func (p *PhidgetFrequencyCounter) GetMinFrequencyCutoff() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getMinFrequencyCutoff(p.handle, r)
	})
}

// GetMaxFrequencyCutoff wraps PhidgetFrequencyCounter_getMaxFrequencyCutoff.
func (p *PhidgetFrequencyCounter) GetMaxFrequencyCutoff() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getMaxFrequencyCutoff(p.handle, r)
	})
}

// SetInputMode wraps PhidgetFrequencyCounter_setInputMode.
func (p *PhidgetFrequencyCounter) SetInputMode(inputMode int) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setInputMode(p.handle, C.Phidget_InputMode(inputMode)))
}

// GetInputMode wraps PhidgetFrequencyCounter_getInputMode.
func (p *PhidgetFrequencyCounter) GetInputMode() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_InputMode) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getInputMode(p.handle, r)
	}, func(r C.Phidget_InputMode) int { return int(r) })
}

// SetPowerSupply wraps PhidgetFrequencyCounter_setPowerSupply.
func (p *PhidgetFrequencyCounter) SetPowerSupply(powerSupply int) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setPowerSupply(p.handle, C.Phidget_PowerSupply(powerSupply)))
}

// GetPowerSupply wraps PhidgetFrequencyCounter_getPowerSupply.
func (p *PhidgetFrequencyCounter) GetPowerSupply() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_PowerSupply) C.PhidgetReturnCode {
		return C.PhidgetFrequencyCounter_getPowerSupply(p.handle, r)
	}, func(r C.Phidget_PowerSupply) int { return int(r) })
}

// GetTimeElapsed wraps PhidgetFrequencyCounter_getTimeElapsed.
func (p *PhidgetFrequencyCounter) GetTimeElapsed() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetFrequencyCounter_getTimeElapsed(p.handle, r) })
}

// SetOnCountChangeHandler wraps PhidgetFrequencyCounter_setOnCountChangeHandler. The handler runs on a C thread.
func (p *PhidgetFrequencyCounter) SetOnCountChangeHandler(f func(uint64, float64)) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setOnCountChangeHandler(p.handle, (C.phidget_count_fcn)(unsafe.Pointer(C.ccountcallback)), p.save(f)))
}

// SetOnFrequencyChangeHandler wraps PhidgetFrequencyCounter_setOnFrequencyChangeHandler. The handler runs on a C thread.
func (p *PhidgetFrequencyCounter) SetOnFrequencyChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetFrequencyCounter_setOnFrequencyChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
