// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetGPS wraps a PhidgetGPS channel.
type PhidgetGPS struct {
	phidget
	handle C.PhidgetGPSHandle
}

// Create creates a PhidgetGPS handle.
func (p *PhidgetGPS) Create() {
	C.PhidgetGPS_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetGPS) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetGPS_delete(&p.handle))
}

// GetAltitude wraps PhidgetGPS_getAltitude.
func (p *PhidgetGPS) GetAltitude() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGPS_getAltitude(p.handle, r) })
}

// GetHeading wraps PhidgetGPS_getHeading.
func (p *PhidgetGPS) GetHeading() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGPS_getHeading(p.handle, r) })
}

// GetLatitude wraps PhidgetGPS_getLatitude.
func (p *PhidgetGPS) GetLatitude() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGPS_getLatitude(p.handle, r) })
}

// GetLongitude wraps PhidgetGPS_getLongitude.
func (p *PhidgetGPS) GetLongitude() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGPS_getLongitude(p.handle, r) })
}

// GetPositionFixState wraps PhidgetGPS_getPositionFixState.
func (p *PhidgetGPS) GetPositionFixState() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetGPS_getPositionFixState(p.handle, r) })
}

// GetVelocity wraps PhidgetGPS_getVelocity.
func (p *PhidgetGPS) GetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGPS_getVelocity(p.handle, r) })
}

// SetOnHeadingChangeHandler wraps PhidgetGPS_setOnHeadingChangeHandler. The handler runs on a C thread.
func (p *PhidgetGPS) SetOnHeadingChangeHandler(f func(float64, float64)) error {
	return p.phidgetError(C.PhidgetGPS_setOnHeadingChangeHandler(p.handle, (C.phidget_twofloat_fcn)(unsafe.Pointer(C.ctwofloatcallback)), p.save(f)))
}

// SetOnPositionChangeHandler wraps PhidgetGPS_setOnPositionChangeHandler. The handler runs on a C thread.
func (p *PhidgetGPS) SetOnPositionChangeHandler(f func(float64, float64, float64)) error {
	return p.phidgetError(C.PhidgetGPS_setOnPositionChangeHandler(p.handle, (C.phidget_threefloat_fcn)(unsafe.Pointer(C.cthreefloatcallback)), p.save(f)))
}
