// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetGyroscope wraps a PhidgetGyroscope channel.
type PhidgetGyroscope struct {
	phidget
	handle C.PhidgetGyroscopeHandle
}

// Create creates a PhidgetGyroscope handle.
func (p *PhidgetGyroscope) Create() {
	C.PhidgetGyroscope_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetGyroscope) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetGyroscope_delete(&p.handle))
}

// Zero wraps PhidgetGyroscope_zero.
func (p *PhidgetGyroscope) Zero() error {
	return p.phidgetError(C.PhidgetGyroscope_zero(p.handle))
}

// GetAngularRate wraps PhidgetGyroscope_getAngularRate.
func (p *PhidgetGyroscope) GetAngularRate() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getAngularRate(p.handle, r) })
}

// GetMinAngularRate wraps PhidgetGyroscope_getMinAngularRate.
func (p *PhidgetGyroscope) GetMinAngularRate() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMinAngularRate(p.handle, r) })
}

// GetMaxAngularRate wraps PhidgetGyroscope_getMaxAngularRate.
func (p *PhidgetGyroscope) GetMaxAngularRate() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMaxAngularRate(p.handle, r) })
}

// GetAxisCount wraps PhidgetGyroscope_getAxisCount.
func (p *PhidgetGyroscope) GetAxisCount() (int, error) {
	return getInt(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetGyroscope_getAxisCount(p.handle, r) })
}

// SetDataInterval wraps PhidgetGyroscope_setDataInterval.
func (p *PhidgetGyroscope) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetGyroscope_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetGyroscope_getDataInterval.
func (p *PhidgetGyroscope) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetGyroscope_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetGyroscope_getMinDataInterval.
func (p *PhidgetGyroscope) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetGyroscope_getMaxDataInterval.
func (p *PhidgetGyroscope) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetGyroscope_setDataRate.
func (p *PhidgetGyroscope) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetGyroscope_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetGyroscope_getDataRate.
func (p *PhidgetGyroscope) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetGyroscope_getMinDataRate.
func (p *PhidgetGyroscope) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetGyroscope_getMaxDataRate.
func (p *PhidgetGyroscope) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getMaxDataRate(p.handle, r) })
}

// SetHeatingEnabled wraps PhidgetGyroscope_setHeatingEnabled.
func (p *PhidgetGyroscope) SetHeatingEnabled(heatingEnabled bool) error {
	return p.phidgetError(C.PhidgetGyroscope_setHeatingEnabled(p.handle, boolToCInt(heatingEnabled)))
}

// GetHeatingEnabled wraps PhidgetGyroscope_getHeatingEnabled.
func (p *PhidgetGyroscope) GetHeatingEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetGyroscope_getHeatingEnabled(p.handle, r) })
}

// GetTimestamp wraps PhidgetGyroscope_getTimestamp.
func (p *PhidgetGyroscope) GetTimestamp() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetGyroscope_getTimestamp(p.handle, r) })
}

// SetOnAngularRateUpdateHandler wraps PhidgetGyroscope_setOnAngularRateUpdateHandler. The handler runs on a C thread.
func (p *PhidgetGyroscope) SetOnAngularRateUpdateHandler(f func([]float64, float64)) error {
	return p.phidgetError(C.PhidgetGyroscope_setOnAngularRateUpdateHandler(p.handle, (C.phidget_motion_fcn)(unsafe.Pointer(C.cmotioncallback)), p.save(f)))
}
