// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetMagnetometer wraps a PhidgetMagnetometer channel.
type PhidgetMagnetometer struct {
	phidget
	handle C.PhidgetMagnetometerHandle
}

// Create creates a PhidgetMagnetometer handle.
func (p *PhidgetMagnetometer) Create() {
	C.PhidgetMagnetometer_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetMagnetometer) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetMagnetometer_delete(&p.handle))
}

// ResetCorrectionParameters wraps PhidgetMagnetometer_resetCorrectionParameters.
func (p *PhidgetMagnetometer) ResetCorrectionParameters() error {
	return p.phidgetError(C.PhidgetMagnetometer_resetCorrectionParameters(p.handle))
}

// SaveCorrectionParameters wraps PhidgetMagnetometer_saveCorrectionParameters.
func (p *PhidgetMagnetometer) SaveCorrectionParameters() error {
	return p.phidgetError(C.PhidgetMagnetometer_saveCorrectionParameters(p.handle))
}

// GetAxisCount wraps PhidgetMagnetometer_getAxisCount.
func (p *PhidgetMagnetometer) GetAxisCount() (int, error) {
	return getInt(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getAxisCount(p.handle, r) })
}

// SetDataInterval wraps PhidgetMagnetometer_setDataInterval.
func (p *PhidgetMagnetometer) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetMagnetometer_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetMagnetometer_getDataInterval.
func (p *PhidgetMagnetometer) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetMagnetometer_getMinDataInterval.
func (p *PhidgetMagnetometer) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetMagnetometer_getMaxDataInterval.
func (p *PhidgetMagnetometer) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetMagnetometer_setDataRate.
func (p *PhidgetMagnetometer) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetMagnetometer_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetMagnetometer_getDataRate.
func (p *PhidgetMagnetometer) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetMagnetometer_getMinDataRate.
func (p *PhidgetMagnetometer) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetMagnetometer_getMaxDataRate.
func (p *PhidgetMagnetometer) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getMaxDataRate(p.handle, r) })
}

// SetHeatingEnabled wraps PhidgetMagnetometer_setHeatingEnabled.
func (p *PhidgetMagnetometer) SetHeatingEnabled(heatingEnabled bool) error {
	return p.phidgetError(C.PhidgetMagnetometer_setHeatingEnabled(p.handle, boolToCInt(heatingEnabled)))
}

// GetHeatingEnabled wraps PhidgetMagnetometer_getHeatingEnabled.
func (p *PhidgetMagnetometer) GetHeatingEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getHeatingEnabled(p.handle, r) })
}

// GetMagneticField wraps PhidgetMagnetometer_getMagneticField.
func (p *PhidgetMagnetometer) GetMagneticField() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getMagneticField(p.handle, r) })
}

// GetMinMagneticField wraps PhidgetMagnetometer_getMinMagneticField.
func (p *PhidgetMagnetometer) GetMinMagneticField() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode {
		return C.PhidgetMagnetometer_getMinMagneticField(p.handle, r)
	})
}

// GetMaxMagneticField wraps PhidgetMagnetometer_getMaxMagneticField.
func (p *PhidgetMagnetometer) GetMaxMagneticField() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode {
		return C.PhidgetMagnetometer_getMaxMagneticField(p.handle, r)
	})
}

// SetMagneticFieldChangeTrigger wraps PhidgetMagnetometer_setMagneticFieldChangeTrigger.
func (p *PhidgetMagnetometer) SetMagneticFieldChangeTrigger(magneticFieldChangeTrigger float64) error {
	return p.phidgetError(C.PhidgetMagnetometer_setMagneticFieldChangeTrigger(p.handle, C.double(magneticFieldChangeTrigger)))
}

// GetMagneticFieldChangeTrigger wraps PhidgetMagnetometer_getMagneticFieldChangeTrigger.
func (p *PhidgetMagnetometer) GetMagneticFieldChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetMagnetometer_getMagneticFieldChangeTrigger(p.handle, r)
	})
}

// GetMinMagneticFieldChangeTrigger wraps PhidgetMagnetometer_getMinMagneticFieldChangeTrigger.
func (p *PhidgetMagnetometer) GetMinMagneticFieldChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetMagnetometer_getMinMagneticFieldChangeTrigger(p.handle, r)
	})
}

// GetMaxMagneticFieldChangeTrigger wraps PhidgetMagnetometer_getMaxMagneticFieldChangeTrigger.
func (p *PhidgetMagnetometer) GetMaxMagneticFieldChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetMagnetometer_getMaxMagneticFieldChangeTrigger(p.handle, r)
	})
}

// GetTimestamp wraps PhidgetMagnetometer_getTimestamp.
func (p *PhidgetMagnetometer) GetTimestamp() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetMagnetometer_getTimestamp(p.handle, r) })
}

// SetOnMagneticFieldChangeHandler wraps PhidgetMagnetometer_setOnMagneticFieldChangeHandler. The handler runs on a C thread.
func (p *PhidgetMagnetometer) SetOnMagneticFieldChangeHandler(f func([]float64, float64)) error {
	return p.phidgetError(C.PhidgetMagnetometer_setOnMagneticFieldChangeHandler(p.handle, (C.phidget_motion_fcn)(unsafe.Pointer(C.cmotioncallback)), p.save(f)))
}
