// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetPHSensor wraps a PhidgetPHSensor channel.
type PhidgetPHSensor struct {
	phidget
	handle C.PhidgetPHSensorHandle
}

// Create creates a PhidgetPHSensor handle.
func (p *PhidgetPHSensor) Create() {
	C.PhidgetPHSensor_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetPHSensor) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetPHSensor_delete(&p.handle))
}

// SetCorrectionTemperature wraps PhidgetPHSensor_setCorrectionTemperature.
func (p *PhidgetPHSensor) SetCorrectionTemperature(correctionTemperature float64) error {
	return p.phidgetError(C.PhidgetPHSensor_setCorrectionTemperature(p.handle, C.double(correctionTemperature)))
}

// GetCorrectionTemperature wraps PhidgetPHSensor_getCorrectionTemperature.
func (p *PhidgetPHSensor) GetCorrectionTemperature() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getCorrectionTemperature(p.handle, r) })
}

// GetMinCorrectionTemperature wraps PhidgetPHSensor_getMinCorrectionTemperature.
func (p *PhidgetPHSensor) GetMinCorrectionTemperature() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetPHSensor_getMinCorrectionTemperature(p.handle, r)
	})
}

// GetMaxCorrectionTemperature wraps PhidgetPHSensor_getMaxCorrectionTemperature.
func (p *PhidgetPHSensor) GetMaxCorrectionTemperature() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetPHSensor_getMaxCorrectionTemperature(p.handle, r)
	})
}

// SetDataInterval wraps PhidgetPHSensor_setDataInterval.
func (p *PhidgetPHSensor) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetPHSensor_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetPHSensor_getDataInterval.
func (p *PhidgetPHSensor) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetPHSensor_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetPHSensor_getMinDataInterval.
func (p *PhidgetPHSensor) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetPHSensor_getMaxDataInterval.
func (p *PhidgetPHSensor) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetPHSensor_setDataRate.
func (p *PhidgetPHSensor) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetPHSensor_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetPHSensor_getDataRate.
func (p *PhidgetPHSensor) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetPHSensor_getMinDataRate.
func (p *PhidgetPHSensor) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetPHSensor_getMaxDataRate.
func (p *PhidgetPHSensor) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMaxDataRate(p.handle, r) })
}

// GetPH wraps PhidgetPHSensor_getPH.
func (p *PhidgetPHSensor) GetPH() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getPH(p.handle, r) })
}

// GetMinPH wraps PhidgetPHSensor_getMinPH.
func (p *PhidgetPHSensor) GetMinPH() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMinPH(p.handle, r) })
}

// GetMaxPH wraps PhidgetPHSensor_getMaxPH.
func (p *PhidgetPHSensor) GetMaxPH() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMaxPH(p.handle, r) })
}

// SetPHChangeTrigger wraps PhidgetPHSensor_setPHChangeTrigger.
func (p *PhidgetPHSensor) SetPHChangeTrigger(PHChangeTrigger float64) error {
	return p.phidgetError(C.PhidgetPHSensor_setPHChangeTrigger(p.handle, C.double(PHChangeTrigger)))
}

// GetPHChangeTrigger wraps PhidgetPHSensor_getPHChangeTrigger.
func (p *PhidgetPHSensor) GetPHChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getPHChangeTrigger(p.handle, r) })
}

// GetMinPHChangeTrigger wraps PhidgetPHSensor_getMinPHChangeTrigger.
func (p *PhidgetPHSensor) GetMinPHChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMinPHChangeTrigger(p.handle, r) })
}

// GetMaxPHChangeTrigger wraps PhidgetPHSensor_getMaxPHChangeTrigger.
func (p *PhidgetPHSensor) GetMaxPHChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPHSensor_getMaxPHChangeTrigger(p.handle, r) })
}

// SetOnPHChangeHandler wraps PhidgetPHSensor_setOnPHChangeHandler. The handler runs on a C thread.
func (p *PhidgetPHSensor) SetOnPHChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetPHSensor_setOnPHChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
