// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetPressureSensor wraps a PhidgetPressureSensor channel.
type PhidgetPressureSensor struct {
	phidget
	handle C.PhidgetPressureSensorHandle
}

// Create creates a PhidgetPressureSensor handle.
func (p *PhidgetPressureSensor) Create() {
	C.PhidgetPressureSensor_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetPressureSensor) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetPressureSensor_delete(&p.handle))
}

// SetDataInterval wraps PhidgetPressureSensor_setDataInterval.
func (p *PhidgetPressureSensor) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetPressureSensor_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetPressureSensor_getDataInterval.
func (p *PhidgetPressureSensor) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetPressureSensor_getMinDataInterval.
func (p *PhidgetPressureSensor) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetPressureSensor_getMinDataInterval(p.handle, r)
	})
}

// GetMaxDataInterval wraps PhidgetPressureSensor_getMaxDataInterval.
func (p *PhidgetPressureSensor) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetPressureSensor_getMaxDataInterval(p.handle, r)
	})
}

// SetDataRate wraps PhidgetPressureSensor_setDataRate.
func (p *PhidgetPressureSensor) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetPressureSensor_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetPressureSensor_getDataRate.
func (p *PhidgetPressureSensor) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetPressureSensor_getMinDataRate.
func (p *PhidgetPressureSensor) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetPressureSensor_getMaxDataRate.
func (p *PhidgetPressureSensor) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getMaxDataRate(p.handle, r) })
}

// GetPressure wraps PhidgetPressureSensor_getPressure.
func (p *PhidgetPressureSensor) GetPressure() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getPressure(p.handle, r) })
}

// GetMinPressure wraps PhidgetPressureSensor_getMinPressure.
func (p *PhidgetPressureSensor) GetMinPressure() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getMinPressure(p.handle, r) })
}

// GetMaxPressure wraps PhidgetPressureSensor_getMaxPressure.
func (p *PhidgetPressureSensor) GetMaxPressure() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetPressureSensor_getMaxPressure(p.handle, r) })
}

// SetPressureChangeTrigger wraps PhidgetPressureSensor_setPressureChangeTrigger.
func (p *PhidgetPressureSensor) SetPressureChangeTrigger(pressureChangeTrigger float64) error {
	return p.phidgetError(C.PhidgetPressureSensor_setPressureChangeTrigger(p.handle, C.double(pressureChangeTrigger)))
}

// GetPressureChangeTrigger wraps PhidgetPressureSensor_getPressureChangeTrigger.
func (p *PhidgetPressureSensor) GetPressureChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetPressureSensor_getPressureChangeTrigger(p.handle, r)
	})
}

// GetMinPressureChangeTrigger wraps PhidgetPressureSensor_getMinPressureChangeTrigger.
func (p *PhidgetPressureSensor) GetMinPressureChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetPressureSensor_getMinPressureChangeTrigger(p.handle, r)
	})
}

// GetMaxPressureChangeTrigger wraps PhidgetPressureSensor_getMaxPressureChangeTrigger.
func (p *PhidgetPressureSensor) GetMaxPressureChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetPressureSensor_getMaxPressureChangeTrigger(p.handle, r)
	})
}

// SetOnPressureChangeHandler wraps PhidgetPressureSensor_setOnPressureChangeHandler. The handler runs on a C thread.
func (p *PhidgetPressureSensor) SetOnPressureChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetPressureSensor_setOnPressureChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
