// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetRCServo wraps a PhidgetRCServo channel.
type PhidgetRCServo struct {
	phidget
	handle C.PhidgetRCServoHandle
}

// Create creates a PhidgetRCServo handle.
func (p *PhidgetRCServo) Create() {
	C.PhidgetRCServo_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetRCServo) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetRCServo_delete(&p.handle))
}

// EnableFailsafe wraps PhidgetRCServo_enableFailsafe.
func (p *PhidgetRCServo) EnableFailsafe(failsafeTime uint32) error {
	return p.phidgetError(C.PhidgetRCServo_enableFailsafe(p.handle, C.uint32_t(failsafeTime)))
}

// ResetFailsafe wraps PhidgetRCServo_resetFailsafe.
func (p *PhidgetRCServo) ResetFailsafe() error {
	return p.phidgetError(C.PhidgetRCServo_resetFailsafe(p.handle))
}

// SetAcceleration wraps PhidgetRCServo_setAcceleration.
func (p *PhidgetRCServo) SetAcceleration(acceleration float64) error {
	return p.phidgetError(C.PhidgetRCServo_setAcceleration(p.handle, C.double(acceleration)))
}

// GetAcceleration wraps PhidgetRCServo_getAcceleration.
func (p *PhidgetRCServo) GetAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getAcceleration(p.handle, r) })
}

// GetMinAcceleration wraps PhidgetRCServo_getMinAcceleration.
func (p *PhidgetRCServo) GetMinAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinAcceleration(p.handle, r) })
}

// GetMaxAcceleration wraps PhidgetRCServo_getMaxAcceleration.
func (p *PhidgetRCServo) GetMaxAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxAcceleration(p.handle, r) })
}

// SetDataInterval wraps PhidgetRCServo_setDataInterval.
func (p *PhidgetRCServo) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetRCServo_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetRCServo_getDataInterval.
func (p *PhidgetRCServo) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetRCServo_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetRCServo_getMinDataInterval.
func (p *PhidgetRCServo) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetRCServo_getMaxDataInterval.
func (p *PhidgetRCServo) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetRCServo_setDataRate.
func (p *PhidgetRCServo) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetRCServo_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetRCServo_getDataRate.
func (p *PhidgetRCServo) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetRCServo_getMinDataRate.
func (p *PhidgetRCServo) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetRCServo_getMaxDataRate.
func (p *PhidgetRCServo) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxDataRate(p.handle, r) })
}

// SetEngaged wraps PhidgetRCServo_setEngaged.
func (p *PhidgetRCServo) SetEngaged(engaged bool) error {
	return p.phidgetError(C.PhidgetRCServo_setEngaged(p.handle, boolToCInt(engaged)))
}

// GetEngaged wraps PhidgetRCServo_getEngaged.
func (p *PhidgetRCServo) GetEngaged() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetRCServo_getEngaged(p.handle, r) })
}

// GetMinFailsafeTime wraps PhidgetRCServo_getMinFailsafeTime.
func (p *PhidgetRCServo) GetMinFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinFailsafeTime(p.handle, r) })
}

// GetMaxFailsafeTime wraps PhidgetRCServo_getMaxFailsafeTime.
func (p *PhidgetRCServo) GetMaxFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxFailsafeTime(p.handle, r) })
}

// GetIsMoving wraps PhidgetRCServo_getIsMoving.
func (p *PhidgetRCServo) GetIsMoving() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetRCServo_getIsMoving(p.handle, r) })
}

// GetPosition wraps PhidgetRCServo_getPosition.
func (p *PhidgetRCServo) GetPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getPosition(p.handle, r) })
}

// SetMinPosition wraps PhidgetRCServo_setMinPosition.
func (p *PhidgetRCServo) SetMinPosition(minPosition float64) error {
	return p.phidgetError(C.PhidgetRCServo_setMinPosition(p.handle, C.double(minPosition)))
}

// GetMinPosition wraps PhidgetRCServo_getMinPosition.
func (p *PhidgetRCServo) GetMinPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinPosition(p.handle, r) })
}

// SetMaxPosition wraps PhidgetRCServo_setMaxPosition.
func (p *PhidgetRCServo) SetMaxPosition(maxPosition float64) error {
	return p.phidgetError(C.PhidgetRCServo_setMaxPosition(p.handle, C.double(maxPosition)))
}

// GetMaxPosition wraps PhidgetRCServo_getMaxPosition.
func (p *PhidgetRCServo) GetMaxPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxPosition(p.handle, r) })
}

// SetMinPulseWidth wraps PhidgetRCServo_setMinPulseWidth.
func (p *PhidgetRCServo) SetMinPulseWidth(minPulseWidth float64) error {
	return p.phidgetError(C.PhidgetRCServo_setMinPulseWidth(p.handle, C.double(minPulseWidth)))
}

// GetMinPulseWidth wraps PhidgetRCServo_getMinPulseWidth.
func (p *PhidgetRCServo) GetMinPulseWidth() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinPulseWidth(p.handle, r) })
}

// SetMaxPulseWidth wraps PhidgetRCServo_setMaxPulseWidth.
func (p *PhidgetRCServo) SetMaxPulseWidth(maxPulseWidth float64) error {
	return p.phidgetError(C.PhidgetRCServo_setMaxPulseWidth(p.handle, C.double(maxPulseWidth)))
}

// GetMaxPulseWidth wraps PhidgetRCServo_getMaxPulseWidth.
func (p *PhidgetRCServo) GetMaxPulseWidth() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxPulseWidth(p.handle, r) })
}

// GetMinPulseWidthLimit wraps PhidgetRCServo_getMinPulseWidthLimit.
func (p *PhidgetRCServo) GetMinPulseWidthLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinPulseWidthLimit(p.handle, r) })
}

// GetMaxPulseWidthLimit wraps PhidgetRCServo_getMaxPulseWidthLimit.
func (p *PhidgetRCServo) GetMaxPulseWidthLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxPulseWidthLimit(p.handle, r) })
}

// SetSpeedRampingState wraps PhidgetRCServo_setSpeedRampingState.
func (p *PhidgetRCServo) SetSpeedRampingState(speedRampingState bool) error {
	return p.phidgetError(C.PhidgetRCServo_setSpeedRampingState(p.handle, boolToCInt(speedRampingState)))
}

// GetSpeedRampingState wraps PhidgetRCServo_getSpeedRampingState.
func (p *PhidgetRCServo) GetSpeedRampingState() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetRCServo_getSpeedRampingState(p.handle, r) })
}

// SetTargetPosition wraps PhidgetRCServo_setTargetPosition.
func (p *PhidgetRCServo) SetTargetPosition(targetPosition float64) error {
	return p.phidgetError(C.PhidgetRCServo_setTargetPosition(p.handle, C.double(targetPosition)))
}

// GetTargetPosition wraps PhidgetRCServo_getTargetPosition.
func (p *PhidgetRCServo) GetTargetPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getTargetPosition(p.handle, r) })
}

// SetTorque wraps PhidgetRCServo_setTorque.
func (p *PhidgetRCServo) SetTorque(torque float64) error {
	return p.phidgetError(C.PhidgetRCServo_setTorque(p.handle, C.double(torque)))
}

// GetTorque wraps PhidgetRCServo_getTorque.
func (p *PhidgetRCServo) GetTorque() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getTorque(p.handle, r) })
}

// GetMinTorque wraps PhidgetRCServo_getMinTorque.
func (p *PhidgetRCServo) GetMinTorque() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinTorque(p.handle, r) })
}

// GetMaxTorque wraps PhidgetRCServo_getMaxTorque.
func (p *PhidgetRCServo) GetMaxTorque() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxTorque(p.handle, r) })
}

// GetVelocity wraps PhidgetRCServo_getVelocity.
func (p *PhidgetRCServo) GetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getVelocity(p.handle, r) })
}

// SetVelocityLimit wraps PhidgetRCServo_setVelocityLimit.
func (p *PhidgetRCServo) SetVelocityLimit(velocityLimit float64) error {
	return p.phidgetError(C.PhidgetRCServo_setVelocityLimit(p.handle, C.double(velocityLimit)))
}

// GetVelocityLimit wraps PhidgetRCServo_getVelocityLimit.
func (p *PhidgetRCServo) GetVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getVelocityLimit(p.handle, r) })
}

// GetMinVelocityLimit wraps PhidgetRCServo_getMinVelocityLimit.
func (p *PhidgetRCServo) GetMinVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMinVelocityLimit(p.handle, r) })
}

// GetMaxVelocityLimit wraps PhidgetRCServo_getMaxVelocityLimit.
func (p *PhidgetRCServo) GetMaxVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetRCServo_getMaxVelocityLimit(p.handle, r) })
}

// SetVoltage wraps PhidgetRCServo_setVoltage.
func (p *PhidgetRCServo) SetVoltage(voltage int) error {
	return p.phidgetError(C.PhidgetRCServo_setVoltage(p.handle, C.PhidgetRCServo_Voltage(voltage)))
}

// GetVoltage wraps PhidgetRCServo_getVoltage.
func (p *PhidgetRCServo) GetVoltage() (int, error) {
	return get(&p.phidget, func(r *C.PhidgetRCServo_Voltage) C.PhidgetReturnCode { return C.PhidgetRCServo_getVoltage(p.handle, r) }, func(r C.PhidgetRCServo_Voltage) int { return int(r) })
}

// SetOnPositionChangeHandler wraps PhidgetRCServo_setOnPositionChangeHandler. The handler runs on a C thread.
func (p *PhidgetRCServo) SetOnPositionChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetRCServo_setOnPositionChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnTargetPositionReachedHandler wraps PhidgetRCServo_setOnTargetPositionReachedHandler. The handler runs on a C thread.
func (p *PhidgetRCServo) SetOnTargetPositionReachedHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetRCServo_setOnTargetPositionReachedHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnVelocityChangeHandler wraps PhidgetRCServo_setOnVelocityChangeHandler. The handler runs on a C thread.
func (p *PhidgetRCServo) SetOnVelocityChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetRCServo_setOnVelocityChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
