// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetResistanceInput wraps a PhidgetResistanceInput channel.
type PhidgetResistanceInput struct {
	phidget
	handle C.PhidgetResistanceInputHandle
}

// Create creates a PhidgetResistanceInput handle.
func (p *PhidgetResistanceInput) Create() {
	C.PhidgetResistanceInput_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetResistanceInput) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetResistanceInput_delete(&p.handle))
}

// SetDataInterval wraps PhidgetResistanceInput_setDataInterval.
func (p *PhidgetResistanceInput) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetResistanceInput_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetResistanceInput_getDataInterval.
func (p *PhidgetResistanceInput) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetResistanceInput_getMinDataInterval.
func (p *PhidgetResistanceInput) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getMinDataInterval(p.handle, r)
	})
}

// GetMaxDataInterval wraps PhidgetResistanceInput_getMaxDataInterval.
func (p *PhidgetResistanceInput) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getMaxDataInterval(p.handle, r)
	})
}

// SetDataRate wraps PhidgetResistanceInput_setDataRate.
func (p *PhidgetResistanceInput) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetResistanceInput_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetResistanceInput_getDataRate.
func (p *PhidgetResistanceInput) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetResistanceInput_getMinDataRate.
func (p *PhidgetResistanceInput) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetResistanceInput_getMaxDataRate.
func (p *PhidgetResistanceInput) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getMaxDataRate(p.handle, r) })
}

// GetResistance wraps PhidgetResistanceInput_getResistance.
func (p *PhidgetResistanceInput) GetResistance() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getResistance(p.handle, r) })
}

// GetMinResistance wraps PhidgetResistanceInput_getMinResistance.
func (p *PhidgetResistanceInput) GetMinResistance() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getMinResistance(p.handle, r) })
}

// GetMaxResistance wraps PhidgetResistanceInput_getMaxResistance.
func (p *PhidgetResistanceInput) GetMaxResistance() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetResistanceInput_getMaxResistance(p.handle, r) })
}

// SetResistanceChangeTrigger wraps PhidgetResistanceInput_setResistanceChangeTrigger.
func (p *PhidgetResistanceInput) SetResistanceChangeTrigger(resistanceChangeTrigger float64) error {
	return p.phidgetError(C.PhidgetResistanceInput_setResistanceChangeTrigger(p.handle, C.double(resistanceChangeTrigger)))
}

// GetResistanceChangeTrigger wraps PhidgetResistanceInput_getResistanceChangeTrigger.
func (p *PhidgetResistanceInput) GetResistanceChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getResistanceChangeTrigger(p.handle, r)
	})
}

// GetMinResistanceChangeTrigger wraps PhidgetResistanceInput_getMinResistanceChangeTrigger.
func (p *PhidgetResistanceInput) GetMinResistanceChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getMinResistanceChangeTrigger(p.handle, r)
	})
}

// GetMaxResistanceChangeTrigger wraps PhidgetResistanceInput_getMaxResistanceChangeTrigger.
func (p *PhidgetResistanceInput) GetMaxResistanceChangeTrigger() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getMaxResistanceChangeTrigger(p.handle, r)
	})
}

// SetRTDWireSetup wraps PhidgetResistanceInput_setRTDWireSetup.
func (p *PhidgetResistanceInput) SetRTDWireSetup(RTDWireSetup int) error {
	return p.phidgetError(C.PhidgetResistanceInput_setRTDWireSetup(p.handle, C.Phidget_RTDWireSetup(RTDWireSetup)))
}

// GetRTDWireSetup wraps PhidgetResistanceInput_getRTDWireSetup.
func (p *PhidgetResistanceInput) GetRTDWireSetup() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_RTDWireSetup) C.PhidgetReturnCode {
		return C.PhidgetResistanceInput_getRTDWireSetup(p.handle, r)
	}, func(r C.Phidget_RTDWireSetup) int { return int(r) })
}

// SetOnResistanceChangeHandler wraps PhidgetResistanceInput_setOnResistanceChangeHandler. The handler runs on a C thread.
func (p *PhidgetResistanceInput) SetOnResistanceChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetResistanceInput_setOnResistanceChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
