// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetSpatial wraps a PhidgetSpatial channel.
type PhidgetSpatial struct {
	phidget
	handle C.PhidgetSpatialHandle
}

// Create creates a PhidgetSpatial handle.
func (p *PhidgetSpatial) Create() {
	C.PhidgetSpatial_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetSpatial) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetSpatial_delete(&p.handle))
}

// ResetMagnetometerCorrectionParameters wraps PhidgetSpatial_resetMagnetometerCorrectionParameters.
func (p *PhidgetSpatial) ResetMagnetometerCorrectionParameters() error {
	return p.phidgetError(C.PhidgetSpatial_resetMagnetometerCorrectionParameters(p.handle))
}

// SaveMagnetometerCorrectionParameters wraps PhidgetSpatial_saveMagnetometerCorrectionParameters.
func (p *PhidgetSpatial) SaveMagnetometerCorrectionParameters() error {
	return p.phidgetError(C.PhidgetSpatial_saveMagnetometerCorrectionParameters(p.handle))
}

// ZeroAlgorithm wraps PhidgetSpatial_zeroAlgorithm.
func (p *PhidgetSpatial) ZeroAlgorithm() error {
	return p.phidgetError(C.PhidgetSpatial_zeroAlgorithm(p.handle))
}

// ZeroGyro wraps PhidgetSpatial_zeroGyro.
func (p *PhidgetSpatial) ZeroGyro() error {
	return p.phidgetError(C.PhidgetSpatial_zeroGyro(p.handle))
}

// GetMinAcceleration wraps PhidgetSpatial_getMinAcceleration.
func (p *PhidgetSpatial) GetMinAcceleration() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMinAcceleration(p.handle, r) })
}

// GetMaxAcceleration wraps PhidgetSpatial_getMaxAcceleration.
func (p *PhidgetSpatial) GetMaxAcceleration() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMaxAcceleration(p.handle, r) })
}

// SetAlgorithm wraps PhidgetSpatial_setAlgorithm.
func (p *PhidgetSpatial) SetAlgorithm(algorithm int) error {
	return p.phidgetError(C.PhidgetSpatial_setAlgorithm(p.handle, C.Phidget_SpatialAlgorithm(algorithm)))
}

// GetAlgorithm wraps PhidgetSpatial_getAlgorithm.
func (p *PhidgetSpatial) GetAlgorithm() (int, error) {
	return get(&p.phidget, func(r *C.Phidget_SpatialAlgorithm) C.PhidgetReturnCode {
		return C.PhidgetSpatial_getAlgorithm(p.handle, r)
	}, func(r C.Phidget_SpatialAlgorithm) int { return int(r) })
}

// SetAlgorithmMagnetometerGain wraps PhidgetSpatial_setAlgorithmMagnetometerGain.
func (p *PhidgetSpatial) SetAlgorithmMagnetometerGain(algorithmMagnetometerGain float64) error {
	return p.phidgetError(C.PhidgetSpatial_setAlgorithmMagnetometerGain(p.handle, C.double(algorithmMagnetometerGain)))
}

// GetAlgorithmMagnetometerGain wraps PhidgetSpatial_getAlgorithmMagnetometerGain.
func (p *PhidgetSpatial) GetAlgorithmMagnetometerGain() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode {
		return C.PhidgetSpatial_getAlgorithmMagnetometerGain(p.handle, r)
	})
}

// GetMinAngularRate wraps PhidgetSpatial_getMinAngularRate.
func (p *PhidgetSpatial) GetMinAngularRate() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMinAngularRate(p.handle, r) })
}

// GetMaxAngularRate wraps PhidgetSpatial_getMaxAngularRate.
func (p *PhidgetSpatial) GetMaxAngularRate() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMaxAngularRate(p.handle, r) })
}

// SetDataInterval wraps PhidgetSpatial_setDataInterval.
func (p *PhidgetSpatial) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetSpatial_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetSpatial_getDataInterval.
func (p *PhidgetSpatial) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetSpatial_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetSpatial_getMinDataInterval.
func (p *PhidgetSpatial) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetSpatial_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetSpatial_getMaxDataInterval.
func (p *PhidgetSpatial) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetSpatial_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetSpatial_setDataRate.
func (p *PhidgetSpatial) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetSpatial_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetSpatial_getDataRate.
func (p *PhidgetSpatial) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetSpatial_getMinDataRate.
func (p *PhidgetSpatial) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetSpatial_getMaxDataRate.
func (p *PhidgetSpatial) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMaxDataRate(p.handle, r) })
}

// SetHeatingEnabled wraps PhidgetSpatial_setHeatingEnabled.
func (p *PhidgetSpatial) SetHeatingEnabled(heatingEnabled bool) error {
	return p.phidgetError(C.PhidgetSpatial_setHeatingEnabled(p.handle, boolToCInt(heatingEnabled)))
}

// GetHeatingEnabled wraps PhidgetSpatial_getHeatingEnabled.
func (p *PhidgetSpatial) GetHeatingEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetSpatial_getHeatingEnabled(p.handle, r) })
}

// GetMinMagneticField wraps PhidgetSpatial_getMinMagneticField.
func (p *PhidgetSpatial) GetMinMagneticField() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMinMagneticField(p.handle, r) })
}

// GetMaxMagneticField wraps PhidgetSpatial_getMaxMagneticField.
func (p *PhidgetSpatial) GetMaxMagneticField() ([]float64, error) {
	return getVec3(&p.phidget, func(r *[3]C.double) C.PhidgetReturnCode { return C.PhidgetSpatial_getMaxMagneticField(p.handle, r) })
}

// SetOnAlgorithmDataHandler wraps PhidgetSpatial_setOnAlgorithmDataHandler. The handler runs on a C thread.
func (p *PhidgetSpatial) SetOnAlgorithmDataHandler(f func([]float64, float64)) error {
	return p.phidgetError(C.PhidgetSpatial_setOnAlgorithmDataHandler(p.handle, (C.phidget_quaternion_fcn)(unsafe.Pointer(C.cquaternioncallback)), p.save(f)))
}

// SetOnSpatialDataHandler wraps PhidgetSpatial_setOnSpatialDataHandler. The handler runs on a C thread.
func (p *PhidgetSpatial) SetOnSpatialDataHandler(f func([]float64, []float64, []float64, float64)) error {
	return p.phidgetError(C.PhidgetSpatial_setOnSpatialDataHandler(p.handle, (C.phidget_spatial_fcn)(unsafe.Pointer(C.cspatialcallback)), p.save(f)))
}
