// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetStepper wraps a PhidgetStepper channel.
type PhidgetStepper struct {
	phidget
	handle C.PhidgetStepperHandle
}

// Create creates a PhidgetStepper handle.
func (p *PhidgetStepper) Create() {
	C.PhidgetStepper_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetStepper) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetStepper_delete(&p.handle))
}

// EnableFailsafe wraps PhidgetStepper_enableFailsafe.
func (p *PhidgetStepper) EnableFailsafe(failsafeTime uint32) error {
	return p.phidgetError(C.PhidgetStepper_enableFailsafe(p.handle, C.uint32_t(failsafeTime)))
}

// AddPositionOffset wraps PhidgetStepper_addPositionOffset.
func (p *PhidgetStepper) AddPositionOffset(positionOffset float64) error {
	return p.phidgetError(C.PhidgetStepper_addPositionOffset(p.handle, C.double(positionOffset)))
}

// ResetFailsafe wraps PhidgetStepper_resetFailsafe.
func (p *PhidgetStepper) ResetFailsafe() error {
	return p.phidgetError(C.PhidgetStepper_resetFailsafe(p.handle))
}

// SetAcceleration wraps PhidgetStepper_setAcceleration.
func (p *PhidgetStepper) SetAcceleration(acceleration float64) error {
	return p.phidgetError(C.PhidgetStepper_setAcceleration(p.handle, C.double(acceleration)))
}

// GetAcceleration wraps PhidgetStepper_getAcceleration.
func (p *PhidgetStepper) GetAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getAcceleration(p.handle, r) })
}

// GetMinAcceleration wraps PhidgetStepper_getMinAcceleration.
func (p *PhidgetStepper) GetMinAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMinAcceleration(p.handle, r) })
}

// GetMaxAcceleration wraps PhidgetStepper_getMaxAcceleration.
func (p *PhidgetStepper) GetMaxAcceleration() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxAcceleration(p.handle, r) })
}

// SetControlMode wraps PhidgetStepper_setControlMode.
func (p *PhidgetStepper) SetControlMode(controlMode int) error {
	return p.phidgetError(C.PhidgetStepper_setControlMode(p.handle, C.PhidgetStepper_ControlMode(controlMode)))
}

// GetControlMode wraps PhidgetStepper_getControlMode.
func (p *PhidgetStepper) GetControlMode() (int, error) {
	return get(&p.phidget, func(r *C.PhidgetStepper_ControlMode) C.PhidgetReturnCode {
		return C.PhidgetStepper_getControlMode(p.handle, r)
	}, func(r C.PhidgetStepper_ControlMode) int { return int(r) })
}

// SetCurrentLimit wraps PhidgetStepper_setCurrentLimit.
func (p *PhidgetStepper) SetCurrentLimit(currentLimit float64) error {
	return p.phidgetError(C.PhidgetStepper_setCurrentLimit(p.handle, C.double(currentLimit)))
}

// GetCurrentLimit wraps PhidgetStepper_getCurrentLimit.
func (p *PhidgetStepper) GetCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getCurrentLimit(p.handle, r) })
}

// GetMinCurrentLimit wraps PhidgetStepper_getMinCurrentLimit.
func (p *PhidgetStepper) GetMinCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMinCurrentLimit(p.handle, r) })
}

// GetMaxCurrentLimit wraps PhidgetStepper_getMaxCurrentLimit.
func (p *PhidgetStepper) GetMaxCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxCurrentLimit(p.handle, r) })
}

// SetDataInterval wraps PhidgetStepper_setDataInterval.
func (p *PhidgetStepper) SetDataInterval(dataInterval uint32) error {
	return p.phidgetError(C.PhidgetStepper_setDataInterval(p.handle, C.uint32_t(dataInterval)))
}

// GetDataInterval wraps PhidgetStepper_getDataInterval.
func (p *PhidgetStepper) GetDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetStepper_getDataInterval(p.handle, r) })
}

// GetMinDataInterval wraps PhidgetStepper_getMinDataInterval.
func (p *PhidgetStepper) GetMinDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetStepper_getMinDataInterval(p.handle, r) })
}

// GetMaxDataInterval wraps PhidgetStepper_getMaxDataInterval.
func (p *PhidgetStepper) GetMaxDataInterval() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxDataInterval(p.handle, r) })
}

// SetDataRate wraps PhidgetStepper_setDataRate.
func (p *PhidgetStepper) SetDataRate(dataRate float64) error {
	return p.phidgetError(C.PhidgetStepper_setDataRate(p.handle, C.double(dataRate)))
}

// GetDataRate wraps PhidgetStepper_getDataRate.
func (p *PhidgetStepper) GetDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getDataRate(p.handle, r) })
}

// GetMinDataRate wraps PhidgetStepper_getMinDataRate.
func (p *PhidgetStepper) GetMinDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMinDataRate(p.handle, r) })
}

// GetMaxDataRate wraps PhidgetStepper_getMaxDataRate.
func (p *PhidgetStepper) GetMaxDataRate() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxDataRate(p.handle, r) })
}

// SetEngaged wraps PhidgetStepper_setEngaged.
func (p *PhidgetStepper) SetEngaged(engaged bool) error {
	return p.phidgetError(C.PhidgetStepper_setEngaged(p.handle, boolToCInt(engaged)))
}

// GetEngaged wraps PhidgetStepper_getEngaged.
func (p *PhidgetStepper) GetEngaged() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetStepper_getEngaged(p.handle, r) })
}

// GetMinFailsafeTime wraps PhidgetStepper_getMinFailsafeTime.
func (p *PhidgetStepper) GetMinFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetStepper_getMinFailsafeTime(p.handle, r) })
}

// GetMaxFailsafeTime wraps PhidgetStepper_getMaxFailsafeTime.
func (p *PhidgetStepper) GetMaxFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxFailsafeTime(p.handle, r) })
}

// SetHoldingCurrentLimit wraps PhidgetStepper_setHoldingCurrentLimit.
func (p *PhidgetStepper) SetHoldingCurrentLimit(holdingCurrentLimit float64) error {
	return p.phidgetError(C.PhidgetStepper_setHoldingCurrentLimit(p.handle, C.double(holdingCurrentLimit)))
}

// GetHoldingCurrentLimit wraps PhidgetStepper_getHoldingCurrentLimit.
func (p *PhidgetStepper) GetHoldingCurrentLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getHoldingCurrentLimit(p.handle, r) })
}

// GetIsMoving wraps PhidgetStepper_getIsMoving.
func (p *PhidgetStepper) GetIsMoving() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetStepper_getIsMoving(p.handle, r) })
}

// GetPosition wraps PhidgetStepper_getPosition.
func (p *PhidgetStepper) GetPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getPosition(p.handle, r) })
}

// GetMinPosition wraps PhidgetStepper_getMinPosition.
func (p *PhidgetStepper) GetMinPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMinPosition(p.handle, r) })
}

// GetMaxPosition wraps PhidgetStepper_getMaxPosition.
func (p *PhidgetStepper) GetMaxPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxPosition(p.handle, r) })
}

// SetRescaleFactor wraps PhidgetStepper_setRescaleFactor.
func (p *PhidgetStepper) SetRescaleFactor(rescaleFactor float64) error {
	return p.phidgetError(C.PhidgetStepper_setRescaleFactor(p.handle, C.double(rescaleFactor)))
}

// GetRescaleFactor wraps PhidgetStepper_getRescaleFactor.
func (p *PhidgetStepper) GetRescaleFactor() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getRescaleFactor(p.handle, r) })
}

// SetTargetPosition wraps PhidgetStepper_setTargetPosition.
func (p *PhidgetStepper) SetTargetPosition(targetPosition float64) error {
	return p.phidgetError(C.PhidgetStepper_setTargetPosition(p.handle, C.double(targetPosition)))
}

// GetTargetPosition wraps PhidgetStepper_getTargetPosition.
func (p *PhidgetStepper) GetTargetPosition() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getTargetPosition(p.handle, r) })
}

// GetVelocity wraps PhidgetStepper_getVelocity.
func (p *PhidgetStepper) GetVelocity() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getVelocity(p.handle, r) })
}

// SetVelocityLimit wraps PhidgetStepper_setVelocityLimit.
func (p *PhidgetStepper) SetVelocityLimit(velocityLimit float64) error {
	return p.phidgetError(C.PhidgetStepper_setVelocityLimit(p.handle, C.double(velocityLimit)))
}

// GetVelocityLimit wraps PhidgetStepper_getVelocityLimit.
func (p *PhidgetStepper) GetVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getVelocityLimit(p.handle, r) })
}

// GetMinVelocityLimit wraps PhidgetStepper_getMinVelocityLimit.
func (p *PhidgetStepper) GetMinVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMinVelocityLimit(p.handle, r) })
}

// GetMaxVelocityLimit wraps PhidgetStepper_getMaxVelocityLimit.
func (p *PhidgetStepper) GetMaxVelocityLimit() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetStepper_getMaxVelocityLimit(p.handle, r) })
}

// SetOnPositionChangeHandler wraps PhidgetStepper_setOnPositionChangeHandler. The handler runs on a C thread.
func (p *PhidgetStepper) SetOnPositionChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetStepper_setOnPositionChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}

// SetOnStoppedHandler wraps PhidgetStepper_setOnStoppedHandler. The handler runs on a C thread.
func (p *PhidgetStepper) SetOnStoppedHandler(f func()) error {
	return p.phidgetError(C.PhidgetStepper_setOnStoppedHandler(p.handle, (C.phidget_void_fcn)(unsafe.Pointer(C.cvoidcallback)), p.save(f)))
}

// SetOnVelocityChangeHandler wraps PhidgetStepper_setOnVelocityChangeHandler. The handler runs on a C thread.
func (p *PhidgetStepper) SetOnVelocityChangeHandler(f func(float64)) error {
	return p.phidgetError(C.PhidgetStepper_setOnVelocityChangeHandler(p.handle, (C.phidget_double_fcn)(unsafe.Pointer(C.ccallback)), p.save(f)))
}
