// Code generated by gen/main.go; DO NOT EDIT.

package phidgets

/*
#include <phidget22.h>
#include "phidgets.h"
*/
import "C"
import "unsafe"

// PhidgetVoltageOutput wraps a PhidgetVoltageOutput channel.
type PhidgetVoltageOutput struct {
	phidget
	handle C.PhidgetVoltageOutputHandle
}

// Create creates a PhidgetVoltageOutput handle.
func (p *PhidgetVoltageOutput) Create() {
	C.PhidgetVoltageOutput_create(&p.handle)
	p.rawHandle(unsafe.Pointer(p.handle))
}

// Close closes the handle and deletes it.
func (p *PhidgetVoltageOutput) Close() error {
	if err := p.phidget.Close(); err != nil {
		return err
	}
	return p.phidgetError(C.PhidgetVoltageOutput_delete(&p.handle))
}

// EnableFailsafe wraps PhidgetVoltageOutput_enableFailsafe.
func (p *PhidgetVoltageOutput) EnableFailsafe(failsafeTime uint32) error {
	return p.phidgetError(C.PhidgetVoltageOutput_enableFailsafe(p.handle, C.uint32_t(failsafeTime)))
}

// ResetFailsafe wraps PhidgetVoltageOutput_resetFailsafe.
func (p *PhidgetVoltageOutput) ResetFailsafe() error {
	return p.phidgetError(C.PhidgetVoltageOutput_resetFailsafe(p.handle))
}

// SetEnabled wraps PhidgetVoltageOutput_setEnabled.
func (p *PhidgetVoltageOutput) SetEnabled(enabled bool) error {
	return p.phidgetError(C.PhidgetVoltageOutput_setEnabled(p.handle, boolToCInt(enabled)))
}

// GetEnabled wraps PhidgetVoltageOutput_getEnabled.
func (p *PhidgetVoltageOutput) GetEnabled() (bool, error) {
	return getBool(&p.phidget, func(r *C.int) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getEnabled(p.handle, r) })
}

// GetMinFailsafeTime wraps PhidgetVoltageOutput_getMinFailsafeTime.
func (p *PhidgetVoltageOutput) GetMinFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getMinFailsafeTime(p.handle, r) })
}

// GetMaxFailsafeTime wraps PhidgetVoltageOutput_getMaxFailsafeTime.
func (p *PhidgetVoltageOutput) GetMaxFailsafeTime() (uint32, error) {
	return getUint32(&p.phidget, func(r *C.uint32_t) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getMaxFailsafeTime(p.handle, r) })
}

// SetVoltage wraps PhidgetVoltageOutput_setVoltage.
func (p *PhidgetVoltageOutput) SetVoltage(voltage float64) error {
	return p.phidgetError(C.PhidgetVoltageOutput_setVoltage(p.handle, C.double(voltage)))
}

// GetVoltage wraps PhidgetVoltageOutput_getVoltage.
func (p *PhidgetVoltageOutput) GetVoltage() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getVoltage(p.handle, r) })
}

// GetMinVoltage wraps PhidgetVoltageOutput_getMinVoltage.
func (p *PhidgetVoltageOutput) GetMinVoltage() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getMinVoltage(p.handle, r) })
}

// GetMaxVoltage wraps PhidgetVoltageOutput_getMaxVoltage.
func (p *PhidgetVoltageOutput) GetMaxVoltage() (float64, error) {
	return getDouble(&p.phidget, func(r *C.double) C.PhidgetReturnCode { return C.PhidgetVoltageOutput_getMaxVoltage(p.handle, r) })
}

// SetVoltageOutputRange wraps PhidgetVoltageOutput_setVoltageOutputRange.
func (p *PhidgetVoltageOutput) SetVoltageOutputRange(voltageOutputRange int) error {
	return p.phidgetError(C.PhidgetVoltageOutput_setVoltageOutputRange(p.handle, C.PhidgetVoltageOutput_VoltageOutputRange(voltageOutputRange)))
}

// GetVoltageOutputRange wraps PhidgetVoltageOutput_getVoltageOutputRange.
func (p *PhidgetVoltageOutput) GetVoltageOutputRange() (int, error) {
	return get(&p.phidget, func(r *C.PhidgetVoltageOutput_VoltageOutputRange) C.PhidgetReturnCode {
		return C.PhidgetVoltageOutput_getVoltageOutputRange(p.handle, r)
	}, func(r C.PhidgetVoltageOutput_VoltageOutputRange) int { return int(r) })
}
